@startuml
!pragma layout smetana
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR
skinparam linetype ortho
top to bottom direction

package Logic {
Class "{abstract}\nCommand" as Command
Class CommandResult

package "Contact Commands" as ContactCommands {
Class AddCommand
Class EditCommand
Class DeleteCommand
Class ViewCommand
Class FindCommand
Class SortCommand
}

package "Encounter Commands" as EncounterCommands {
Class LogCommand
Class EditEncounterCommand
Class RemindCommand
Class ExportCommand
}

package "System Commands" as SystemCommands {
Class ListCommand
Class ClearCommand
Class HelpCommand
Class ExitCommand
}

Class "EditCommand.EditPersonDescriptor" as EditPersonDescriptor
Class "EditEncounterCommand.EditEncounterDescriptor" as EditEncounterDescriptor
Class "<<enumeration>>\nSortCriterion" as SortCriterion
Class "Predicate<Person>" as PersonPredicate
}

package Model {
Class "<<interface>>\nModel" as Model
Class Person
Class Encounter
Class Reminder
}

ContactCommands -[hidden]down-> EncounterCommands
EncounterCommands -[hidden]down-> SystemCommands
AddCommand -[hidden]down-> EditCommand
EditCommand -[hidden]down-> DeleteCommand
DeleteCommand -[hidden]down-> ViewCommand
ViewCommand -[hidden]down-> FindCommand
FindCommand -[hidden]down-> SortCommand

LogCommand -[hidden]down-> EditEncounterCommand
EditEncounterCommand -[hidden]down-> RemindCommand
RemindCommand -[hidden]down-> ExportCommand

ListCommand -[hidden]down-> ClearCommand
ClearCommand -[hidden]down-> HelpCommand
HelpCommand -[hidden]down-> ExitCommand

AddCommand -up-|> Command
EditCommand -up-|> Command
DeleteCommand -up-|> Command
ViewCommand -up-|> Command
LogCommand -up-|> Command
EditEncounterCommand -up-|> Command
RemindCommand -up-|> Command
FindCommand -up-|> Command
SortCommand -up-|> Command
ExportCommand -up-|> Command
ListCommand -up-|> Command
ClearCommand -up-|> Command
HelpCommand -up-|> Command
ExitCommand -up-|> Command

EditCommand *--> "1" EditPersonDescriptor : descriptor
EditEncounterCommand *--> "1" EditEncounterDescriptor : descriptor
SortCommand *--> "1" SortCriterion : criterion
FindCommand --> "1" PersonPredicate : predicate
AddCommand --> "1" Person : toAdd
LogCommand --> "1" Encounter : encounter
RemindCommand --> "1" Reminder : reminder

Command .down.> Model : execute(model)
Command .left.> CommandResult : <<create>>
ViewCommand ..> Person : returned in

@enduml
